### ISSUE TITLE
Why doesn't the FPS counter work with SX OS?

### ISSUE THREAD

**Issue by Hectorim** [masagrator/Status-Monitor-Overlay#4]
I'm a bit confused. Both SaltyNX and SMO work on SX OS, even if they're not officially supported.

Is there a software-related issue that prevents the FPS counter from showing on the overlay, even after SaltyNX and NX-FPS are installed?

**Comment by masagrator** [comment]
Yes. Lack of public API for SX OS Cheat Engine. SX OS didn't share any way to use their cheat engine for other homebrews.

To access FPS in game memory, I'm using Atmosphere's reimplementation of dmnt which includes dmnt:cht. SX OS doesn't have that, so calling it results in stubbed overlay (the same happens if you will try to load Edizon Overlay). That's why I needed to update code to check if Atmosphere is in use. If not, I'm avoiding dmnt:cht to not hang overlay.
