### ISSUE TITLE
the real RAM freq is not reading correctly above 1600, ver 1.0.0

### ISSUE THREAD

**Issue by WE1ZARD** [masagrator/Status-Monitor-Overlay#67]
the real RAM freq is not reading correctly above 1600, (target 2502 shows -1787.-3/-1787.-4)
tested both with rc4 and b6 and the reading is fine in sys-clk overlays.

AMS 1.6.2 FW16.03/FW 17.0

**Comment by masagrator** [comment]
It's definitely not "above 1600" as it works fine at 1996. Can you provide more specific value above which this happens?

**Comment by masagrator** [comment]
Ah, okay. I see the issue in code. It's for anything above int32_max.

**Comment by masagrator** [comment]
For tests 
[Status-Monitor-Overlay.zip](https://github.com/masagrator/Status-Monitor-Overlay/files/13324480/Status-Monitor-Overlay.zip)
If I will find anybody else who will test it before you that will confirm issue is fixed, I will close this and upload that as shadow update.

**Comment by WE1ZARD** [comment]
the issues seems fixed with the test ovl, now it read 2502 correctly, i will test other freq and feedback here.

**Comment by masagrator** [comment]
Since everything else follow the same pattern, next issue will come if we will get anything to work at >4.2 GHz or difference between two clocks will be higher than 2.1 GHz which I bet will never happen. :P Thanks for making this issue, this bug shouldn't happen to begin with if I would think of that solution first when trying to fix why deltas are not converting to signed integers.

**Comment by masagrator** [comment]
Uploaded shadow update fixing your issue + one more that will come out because of that fix eventually.
